# Generated by Django 4.2.30 on 2026-07-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_notification_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor/Nurse'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
