# Generated by Django 4.2.30 on 2026-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_available_doctor_bio_doctor_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='citizenship_card',
            field=models.FileField(blank=True, null=True, upload_to='doctor_docs/citizenship/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_license',
            field=models.FileField(blank=True, null=True, upload_to='doctor_docs/licenses/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='doctor_docs/recommendations/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
